insert into user_tb(username, password, email, created_at) values('ssar', '1234', 'ssar@nate.com', now());
insert into user_tb(username, password, email, created_at) values('cos', '1234', 'cos@nate.com', now());
insert into user_tb(username, password, email, created_at) values('love', '1234', 'love@nate.com', now());
insert into user_tb(username, password, email, created_at) values('a', '1234', 'a@nate.com', now());
insert into user_tb(username, password, email, created_at) values('b', '1234', 'b@nate.com', now());
insert into user_tb(username, password, email, created_at) values('c', '1234', 'c@nate.com', now());
insert into user_tb(username, password, email, created_at) values('d', '1234', 'd@nate.com', now());
insert into user_tb(username, password, email, created_at) values('e', '1234', 'e@nate.com', now());
insert into user_tb(username, password, email, created_at) values('f', '1234', 'f@nate.com', now());
insert into user_tb(username, password, email, created_at) values('g', '1234', 'g@nate.com', now());

insert into board_tb(title,user_id,created_at) values('첫번째 글입니다',1,now());
insert into board_tb(title,user_id,created_at) values('두번째 글입니다',1,now());
insert into board_tb(title,user_id,created_at) values('세번째 글입니다',1,now());
insert into board_tb(title,user_id,created_at) values('넷번째 글입니다',1,now());
insert into board_tb(title,user_id,created_at) values('다섯번째 글입니다',1,now());
insert into board_tb(title,user_id,created_at) values('여섯번째 글입니다',2,now());
insert into board_tb(title,user_id,created_at) values('일곱번째 글입니다',2,now());
insert into board_tb(title,user_id,created_at) values('여덟번째 글입니다',2,now());
insert into board_tb(title,user_id,created_at) values('아홉번째 글입니다',2,now());
insert into board_tb(title,user_id,created_at) values('열번째 글입니다',2,now());
commit;